services:
  postgres:
    image: postgres:15-alpine
    container_name: pi_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre123
      POSTGRES_DB: projeto_pi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/infra/database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/infra/database/populate.sql:/docker-entrypoint-initdb.d/populate.sql

  redis:
    image: redis:7-alpine
    container_name: pi_redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  api:
    build: .
    container_name: pi_api
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgre123@postgres:5432/projeto_pi
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
